language: node_js

node_js:
  - "9"

cache:
  directories:
    - "node_modules"

notifications:
  email: false
  slack: shyftplanteam:ytcBo8O4FsF6i11yzoCmfvTU

# install peer dependency
before_script:
  - npm install vuex --no-save
# tests
script: jest
# tslint
script: ./node_modules/.bin/tslint -p tsconfig.json -c tslint.json
# type checking via tsc
script: ./node_modules/.bin/tsc --noEmit
